name: Manually deploy
on:
  repository_dispatch:
    # microCMSのWebhookトリガーイベント名
    types: [updated-note]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ここで環境を指定
    environment:
      name: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        env:
          NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN: ${{ secrets.NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN }}
          NEXT_PUBLIC_MICROCMS_API_KEY: ${{ secrets.NEXT_PUBLIC_MICROCMS_API_KEY }}
        run: npm run build
      - name: Debug
        run: |
          echo "Bucket: ${{ secrets.AWS_S3_BUCKET }}"
          echo "CF ID: ${{ secrets.AWS_CF_ID }}"
          echo "Bucket: ${{ secrets.ACCESS_KEY_ID }}"
          echo "CF ID: ${{ secrets.SECRET_ACCESS_KEY }}"
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region ap-northeast-1 ./out s3://${{ secrets.AWS_S3_BUCKET}} --delete
          echo "AWS CF reset"
          aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id ${{ secrets.AWS_CF_ID }} --paths "/*"
